import { StyleSheet } from "react-native";
import {
  wp,
  hp,
  colors,
  fontSize,
  fontFamily,
  radius,
} from "../../../../constant"

const styles = StyleSheet.create({
  scrollViewContent: {
    flexGrow: 1,
    backgroundColor: colors.DarkWhite,
    paddingHorizontal: wp(4),
    paddingBottom: hp(4),
  },
  image: {
    height: hp(45),
    width: '100%',
    resizeMode: 'cover',
    borderRadius: radius.radius1,
  },
  headerWrapper: {
    width: '100%',
    borderColor: colors.headerborder,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: hp(1),
    justifyContent: 'space-between',
    width: '100%',
  },
  backButton: {
    height: hp(5),
    width: hp(5),
    backgroundColor: colors.lightGray,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconButton: {
    width: wp(10),
    height: wp(10),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.lightBlue,
    borderRadius: radius.radius5,
  },
  title: {
    fontFamily: fontFamily.bold,
    fontSize: fontSize.medium,
    color: colors.Black,
    textAlign: 'center',
  },
  iconcontainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2),
  },
  stockcontainer: {
    backgroundColor: colors.transparent,
    borderRadius: radius.radius4,
    paddingHorizontal: wp(3.5),
    paddingVertical: hp(0.7),
    position: 'absolute',
    top: hp(1.5),
    right: wp(10),
  },
  stockText: {
    fontFamily: fontFamily.bold,
    fontSize: fontSize.regSmall,
    color: colors.primaryColor,
    fontWeight: '700',
  },
  imageContainer: {
    marginTop: hp(2),
  },
  squarecontainer: {
    height: hp(6),
    width: wp(13),
    backgroundColor: colors.darkgrey,
    borderRadius: radius.radius1,
    marginRight: wp(1.5),
  },
  squareList: {
    marginTop: hp(2),
  },
  priceBox: {
    padding: hp(2),
    borderWidth: 1,
    borderColor: colors.greyborder,
    marginTop: hp(2),
    borderRadius: radius.radius2,
    gap: hp(2),
  },
  priceText: {
    fontFamily: fontFamily.bold,
    fontSize: fontSize.medium,
    color: colors.primaryColor,
    fontWeight: '700',
  },
  quantityRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  quantityLabel: {
    fontSize: fontSize.small,
    fontFamily: fontFamily.medium,
    color: colors.Black,
  },
  quantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(3),
  },
  minusButton: {
    height: hp(3),
    width: hp(3),
    backgroundColor: colors.lightGray,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: radius.radius1,
  },
  minusText: {
    fontSize: fontSize.medium,
    fontFamily: fontFamily.bold,
    color: colors.Black,
    fontWeight: '700',
    bottom: hp(0.5),
  },
  quantityValue: {
    fontSize: fontSize.small,
    fontFamily: fontFamily.bold,
    color: colors.Black,
  },
  plusButton: {
    height: hp(3),
    width: hp(3),
    backgroundColor: colors.primaryColor,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: radius.radius1,
  },
  plusText: {
    fontSize: fontSize.small,
    fontFamily: fontFamily.bold,
    color: colors.DarkWhite,
    fontWeight: '700',
    bottom: hp(0.1),
  },
  addToCartButton: {
    paddingVertical: hp(2.3),
  },
  buttonText: {
    fontSize: fontSize.regSmall,
    fontFamily: fontFamily.medium,
    color: colors.DarkWhite,
  },
  reviewBox: {
    padding: hp(2),
    borderWidth: 1,
    borderColor: colors.bordergrey,
    marginTop: hp(2),
    borderRadius: radius.radius2,
    gap: hp(2),
  },
  reviewTitle: {
    fontFamily: fontFamily.medium,
    fontSize: fontSize.statusSize,
    color: colors.Black,
    fontWeight: '500',
  },
  reviewHeader: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(1),
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2),
  },
  ratingValue: {
    fontSize: fontSize.small,
    color: colors.primaryColor,
    fontWeight: '500',
  },
  reviewCount: {
    fontSize: fontSize.small,
    color: colors.darkestgrey,
    fontWeight: '400',
  },
  reviewText: {
    fontSize: fontSize.small,
    color: colors.darkestgrey,
    fontFamily: fontFamily.DMreg,
  },
  readMore: {
    color: colors.primaryColor,
    fontWeight: '600',
    fontSize: fontSize.small,
  },
  specTitle: {
    fontFamily: fontFamily.medium,
    fontSize: fontSize.statusSize,
    color: colors.Black,
    fontWeight: '500',
    marginBottom:hp(2)
  },
  specRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2),
  },
  specDot: {
    height: wp(1),
    width: wp(1),
    backgroundColor: colors.darkestgrey,
    borderRadius: radius.radius5,
  },
  specText: {
    fontSize: fontSize.avgSmall,
    color: colors.darkestgrey,
    fontFamily: fontFamily.DMreg,
  },
});
export default styles;